carla first commit
JdeRobot/RL-Studio pull request #160
Opened 2023-01-26 20:44 UTC by pjfernandecabo

fix #159 

Adding necessary files to integrate Carla environment in RL-Studio

2023-01-31 21:37 UTC, pjfernandecabo commented
Do not merge yet, I am working on it

2023-03-03 13:01 UTC, sergiopaniego requested changes
- [x]  Remove files starting with point `rl_studio/._rl-studio-tuning-qlearn-followlane.py`...
- [ ]  Should the checkpoint files be deleted?
- [x]  Is `rl_studio/envs/carla/followlane/followlane_env_old.py` needed? 
- [x] Update ` rl_studio/envs/carla/utils/constants.py` file side it has legacy code

2023-03-03 15:15 UTC, pjfernandecabo commented
Is rl_studio/envs/carla/followlane/followlane_env_old.py needed?: no, I've just deleted it.
 Should the checkpoint files be deleted?: I think there are several Gazebo models that it is interesting to keep them here.

2023-03-03 15:36 UTC, sergiopaniego approved these changes

2023-03-03 15:36 UTC, merged